TRUNCATE playnite_change,
    playnite_category,
    playnite_genre,
    playnite_platform,
    playnite_platform_diff,
    playnite_company,
    playnite_feature,
    playnite_tag,
    playnite_series,
    playnite_age_rating,
    playnite_region,
    playnite_source,
    playnite_comp_status,
    playnite_filter_preset,
    playnite_game,
    playnite_game_diff
    RESTART IDENTITY;